version: '3.8'

services:
  app:
    build: .
    image: training
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    command: tail -f /dev/null